### ISSUE TITLE
Option won't get created

### ISSUE THREAD

**Issue by UVLabs** [mathetos/demo-delayed-admin-notice-plugin#5]
For this line: https://github.com/mathetos/demo-delayed-admin-notice-plugin/blob/master/plugin.php#L23

Don't you mean 
`if ( ! function_exists( 'your_prefix_set_review_trigger_date' ) ) {` ?

The option in the DB wouldn't get created otherwise since currently you are checking for the function before you create it. I had to make that change to get the option to be created in the DB @mathetos @ahmadawais

**Comment by mathetos** [comment]
@UVLabs no, I only want it to move forward if that function EXISTS. If it doesn't exist, nothing happens.
